lang: bash
before_install:
- echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list
- sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
- sudo apt-get update
- sudo apt-get install curl jq sed git aptly
- gem install fpm
script:
- "./update-packages"
env:
  global:
    secure: jpb6p/DgecADp7Rk5MpD8ll2Bgl4h+jklsQF1AUrX58e9qQ6u5oSbAFTmOFnotINjYOVfh5VbCSVYGBKV68XUqWLVhd/48vTMJtkNROCTDRahqsWR6wKPSwrXtQ1JjWXqxsVuW8focfRqIfLG69eEQFeLW9BbXoR/mLwAhNfpRuLZl9hDrLxUEViIWO0CEmIEW/ZcgBxAbOni6UwxQcYu4wMl6Xwxw7GX9SPa7h7/UcxhAOcV9UPVynBc1kiJGJQou93TRVchSWHCYTeo+LG+fisfWMC/EYuIxU68e8cQAxN7hoXmX/dtWXYOfGNu1PoGhoh1wN/+uBXVVo9DOUdLz3hqU8GlY/ZzvYxLIB/kKHkO9IggHmxSYvjkzo7xIw659MOPEapu2KLy9Uz8MPncCEXvCJYpK75kUGZ0ugAdVJJwTff5wAdmoymI3b1v8Csd24CFYfIFGo9/3c8rWtD8tpvfhVVLJLEDkTCkSN47zXWZtIXuJrWGjdp6UqtCpSaor8PypxVjpldE56fEqBi+12kywvU8jgLSV6r0moN+si7J5KWR6QzhqYkCeFIuKZELrf9ZFYuEuGHozMKXlKwQjWDsQN8mrKRzrHEIJaFfEymMWD1SBqKTyuXXrcs6uk5FgJ/8KuoWcLWM8YKq3yZHfDLjQTOblYmQHB2jq2zG0U=
